### ISSUE TITLE
App launches on wrong display

### ISSUE THREAD

**Issue by kstrange62** [Looking-Glass/LightfieldPhoto_Issues#7]
Every time I launch the app, it opens on one of the other monitors that is hooked up to my computer instead of the looking glass. It's always the same monitor no matter what settings I pick in the Unity launcher. I've tried a few other apps in the library and they open on the looking glass correctly.

**Comment by alxdncn** [comment]
Hi! This should now be fixed, an update to the app went out yesterday via the Library (the direct download on the site will be updated next week).

NOTE THOUGH! Updating will overwrite your existing quilts and photosets, so please back them up first! From this release on (v1.1.1) that won't be an issue, but it is for this release.
